Repository SwapnilSoni1999/express-dry, pull requests merged in 2021-10, with the labels that each got.

#11 Added Social Security Number validator
  types.js
  validators/SSN_US.js
Labels: hacktoberfest, hacktoberfest2021

#14 added Passport number validator
  types.js
  validators/passport.js
Labels: hacktoberfest, hacktoberfest2021

#20 min max validator for numbers
  helpers/buildDrySchema.js
  tests/config.spec.js
  tests/validators.test.js
Labels: enhancement, hacktoberfest, hacktoberfest2021

#29 Update README | Added a complete example
  README.md
Labels: hacktoberfest-accepted
